from enum import IntEnum


class Terrain(IntEnum):
    EMPTY = -1
    MOUNTAIN = -2
    FOG = -3
    FOG_OBSTACLE = -4
    OFF_LIMITS = -5


INITIAL_WAIT_TURNS = 23
REINFORCEMENT_INTERVAL = 50
SPREADING_TIMES = 4
ATTACK_TURNS_BEFORE_REINFORCEMENTS = 10
RUSH_COLLECT_TURNS = 20
