from enum import IntEnum


class Terrain(IntEnum):
    EMPTY = -1
    MOUNTAIN = -2
    FOG = -3
    FOG_OBSTACLE = -4
    OFF_LIMITS = -5


INITIAL_WAIT_TURNS = 23
REINFORCEMENT_INTERVAL = 50
SPREADING_TIMES = 4
RUSH_COLLECT_TURNS = 20
GENERAL_DEFENSE_RADIUS = 4
GENERAL_MIN_GARRISON = 5
MAX_GENERAL_GARRISON = 20
OFFENSIVE_SOURCE_LIMIT = 12
